spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LibraryManagementSystem
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # or create-drop for development
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect